# Generated by Django 5.2 on 2025-04-11 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="merchant",
            name="owners_name",
        ),
    ]
