# Generated by Django 5.2 on 2025-04-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_merchant_owners_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Merchant",
        ),
    ]
