# Generated by Django 5.2 on 2025-04-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "restaurant_name",
                    models.CharField(max_length=100, verbose_name="Restaurant Name"),
                ),
                (
                    "restaurant_contact_name",
                    models.CharField(max_length=100, verbose_name="Contact Name"),
                ),
                (
                    "contact_number",
                    models.CharField(
                        max_length=15, verbose_name="Primary Contact Number"
                    ),
                ),
                (
                    "secondary_contact_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Secondary Contact Number",
                    ),
                ),
                ("city", models.CharField(max_length=50)),
                ("restaurant_address", models.TextField(verbose_name="Address")),
                ("cuisine", models.CharField(max_length=100)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
