# Generated by Django 5.2 on 2025-04-13 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0002_restaurant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="merchant",
            name="company_name",
        ),
    ]
