# Generated by Django 5.2 on 2025-04-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0004_appuser_remove_restaurant_restaurant_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delivery",
            options={"verbose_name_plural": "Deliveries"},
        ),
        migrations.AddField(
            model_name="merchant",
            name="company_name",
            field=models.CharField(max_length=400, null=True),
        ),
    ]
