# Generated by Django 5.2 on 2025-04-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0005_alter_delivery_options_merchant_company_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="merchant",
            name="company_name",
        ),
    ]
