# Generated by Django 5.2 on 2025-04-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0006_remove_merchant_company_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cuisine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cuisine", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="restaurant",
            old_name="store_address",
            new_name="restaurant_address",
        ),
        migrations.RenameField(
            model_name="restaurant",
            old_name="store_contact_name",
            new_name="restaurant_contact_name",
        ),
        migrations.RenameField(
            model_name="restaurant",
            old_name="store_name",
            new_name="restaurant_name",
        ),
    ]
