# Generated by Django 5.2 on 2025-04-15 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0007_cuisine_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cuisine",
            old_name="cuisine",
            new_name="cuisine_name",
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="cuisine",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cuisine",
                to="merchant.cuisine",
            ),
        ),
    ]
