# Generated by Django 5.2 on 2025-05-01 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0008_rename_cuisine_cuisine_cuisine_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="name",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="cuisine",
            field=models.ForeignKey(
                default="Nepali",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cuisine",
                to="merchant.cuisine",
            ),
        ),
    ]
