# Generated by Django 5.2 on 2025-05-03 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0009_merchant_name_alter_restaurant_cuisine"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Vehicletype",
                    models.CharField(
                        choices=[("Scooter", "Scooter"), ("Bike", "Bike")]
                    ),
                ),
                (
                    "VehicleDocuments",
                    models.CharField(
                        choices=[
                            ("Passport", "Passport"),
                            ("Citizenship", "Citizenship"),
                            ("Driving License", "Driving License"),
                        ]
                    ),
                ),
                ("VehicleNumberplate", models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name="Deliveryman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Firstname", models.CharField(max_length=100)),
                ("Lastname", models.CharField(max_length=100)),
                ("Email", models.EmailField(max_length=254)),
                (
                    "DeliveryType",
                    models.CharField(
                        choices=[
                            ("Freelance", "Freelancer"),
                            ("Salarybased", "Salarybased"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "Zone",
                    models.CharField(
                        choices=[
                            ("Kathmandu", "Kathmandu"),
                            ("Bhaktapur", "Bhaktapur"),
                        ],
                        max_length=20,
                    ),
                ),
                ("IdentityNumber", models.IntegerField()),
                ("IdentityImage", models.ImageField(upload_to="identity_images/")),
                ("PanNumber", models.IntegerField()),
                (
                    "DutyTime",
                    models.CharField(
                        choices=[
                            ("day", "Day (10AM-6PM)"),
                            ("night", "Night (6PM-2AM)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("DateofBirth", models.DateField()),
                ("BillBookScanCopy", models.ImageField(upload_to="bill_book_images/")),
                ("UserImage", models.ImageField(upload_to="user_images/")),
                (
                    "Vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchant.deliveryvehicle",
                    ),
                ),
            ],
        ),
    ]
