# Generated by Django 5.2 on 2025-05-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0010_deliveryvehicle_deliveryman"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryman",
            name="Vehicle",
            field=models.CharField(choices=[("Scooter", "Scooter"), ("Bike", "Bike")]),
        ),
        migrations.AddField(
            model_name="deliveryman",
            name="DocumentType",
            field=models.CharField(
                choices=[
                    ("Passport", "Passport"),
                    ("Citizenship", "Citizenship"),
                    ("Driving License", "Driving License"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="deliveryman",
            name="VehicleNumber",
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.DeleteModel(
            name="DeliveryVehicle",
        ),
    ]
