# Generated by Django 5.2 on 2025-05-03 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "merchant",
            "0011_alter_deliveryman_vehicle_deliveryman_documenttype_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliveryman",
            old_name="DocumentType",
            new_name="IdentityType",
        ),
    ]
