# Generated by Django 5.2 on 2025-05-03 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0013_alter_deliveryman_identitynumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryman",
            name="IdentityNumber",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid Citizenship, Passport, or License number.",
                        regex="^(?:\\d{5}/\\d{1,3}|\\d{7,10}|[A-Z]{1}\\d{7}|[0-9]{2}-[0-9]{2}-\\d{6,8})$",
                    )
                ],
            ),
        ),
    ]
