# Generated by Django 5.2 on 2025-05-03 05:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0014_alter_deliveryman_identitynumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryman",
            name="IdentityNumber",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="deliveryman",
            name="IdentityType",
            field=models.CharField(
                choices=[
                    ("Citizenship", "Citizenship"),
                    ("Driving License", "Driving License"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryman",
            name="PanNumber",
            field=models.CharField(
                help_text="Enter a 9-digit PAN number issued by IRD Nepal.",
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid 9-digit PAN number", regex="^\\d{9}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="deliveryman",
            name="VehicleNumber",
            field=models.CharField(
                max_length=13,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid vehicle number",
                        regex="^(?:[A-Z]{1,2}\\s?\\d\\s?[A-Z]{1,2}\\s?\\d{1,4}|\\d{1,2}-\\d{1,2}-[A-Za-z]{1,3}-\\d{1,4})$",
                    )
                ],
            ),
        ),
    ]
