# Generated by Django 5.2 on 2025-05-03 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0015_alter_deliveryman_identitynumber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryman",
            name="Email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="deliveryman",
            name="VehicleNumber",
            field=models.CharField(
                help_text="Enter the vehicle number in capital letters (e.g., BA 2 PA 1234 or 3-01-Pa-1234).",
                max_length=13,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid vehicle number",
                        regex="^(?:[A-Z]{1,2}\\s?\\d\\s?[A-Z]{1,2}\\s?\\d{1,4}|\\d{1,2}-\\d{1,2}-[A-Za-z]{1,3}-\\d{1,4})$",
                    )
                ],
            ),
        ),
    ]
