# Generated by Django 5.2 on 2025-05-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0016_alter_deliveryman_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryman",
            name="Vehicle",
            field=models.CharField(
                choices=[("Scooter", "Scooter"), ("Bike", "Bike")], max_length=20
            ),
        ),
    ]
