# Generated by Django 5.2 on 2025-05-03 06:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0017_alter_deliveryman_vehicle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryman",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveryman_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryman",
            name="VehicleNumber",
            field=models.CharField(
                help_text="Enter the vehicle number in capital letters (e.g., BA 2 PA 1234 or 3-01-Pa-1234).",
                max_length=13,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid vehicle number",
                        regex="^(?:[A-Z]{1,2}\\s?\\d{1,2}\\s?[A-Z]{1,2}\\s?\\d{1,4}|\\d{1,2}-\\d{1,2}-[A-Za-z]{1,3}-\\d{1,4})$",
                    )
                ],
            ),
        ),
    ]
