# Generated by Django 5.2 on 2025-05-09 06:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0018_deliveryman_user_alter_deliveryman_vehiclenumber"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="city",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="contact_number",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="restaurant_contact_name",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="secondary_contact_number",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="business_plan",
            field=models.CharField(
                choices=[
                    ("commission", "Commission Base"),
                    ("subscription", "Subscription Base"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="cover_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="restaurant/cover_photos/"
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="menu",
            field=models.FileField(null=True, upload_to="restaurant/menus/"),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="owner_contact",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="owner_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="restaurant/profile_pics/"
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restaurant_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="vat_and_tax",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="cuisine",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="longitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="restaurant_address",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="restaurant_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
