# Generated by Django 5.2 on 2025-05-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0020_deliveryman_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryman",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
