# Generated by Django 4.2.7 on 2025-07-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0024_customuser_fooditem_availability_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='review_rating',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rate the food item from 0 to 5', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='external_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
