# Generated by Django 4.2.7 on 2025-07-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0025_fooditem_review_rating_restaurant_external_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='external_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
