# Generated by Django 4.2.7 on 2025-08-01 07:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0026_fooditem_external_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='assigned_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total price for this order', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='FoodOrderCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_orders', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_count', to='merchant.fooditem')),
            ],
            options={
                'verbose_name': 'Food Order Count',
                'verbose_name_plural': 'Food Order Counts',
            },
        ),
    ]
