# Generated by Django 4.2.7 on 2025-08-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0027_alter_delivery_assigned_time_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='delivery_status',
        ),
    ]
