# Generated by Django 5.2 on 2025-08-02 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0028_remove_fooditem_delivery_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliverystatus",
            name="user",
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="deliverystatus",
            name="deliveryman",
        ),
        migrations.RemoveField(
            model_name="deliverystatus",
            name="order",
        ),
        migrations.RemoveField(
            model_name="deliverystatus",
            name="restaurant",
        ),
        migrations.DeleteModel(
            name="AppUser",
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
        migrations.DeleteModel(
            name="DeliveryStatus",
        ),
    ]
