# Generated by Django 5.2 on 2025-08-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0031_alter_order_user"),
        ("merchant", "0031_alter_order_user_cart"),
    ]

    operations = []
