# Generated by Django 5.2 on 2025-08-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0032_merge_20250802_1611"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="order",
            name="is_transited",
            field=models.BooleanField(
                default=True, help_text="Whether the order is in transit/delivered"
            ),
        ),
    ]
