# Generated by Django 5.2 on 2025-09-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0033_remove_order_created_at_remove_order_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryman",
            name="DeliveryType",
        ),
        migrations.RemoveField(
            model_name="deliveryman",
            name="Email",
        ),
        migrations.RemoveField(
            model_name="deliveryman",
            name="IdentityImage",
        ),
        migrations.RemoveField(
            model_name="deliveryman",
            name="IdentityNumber",
        ),
        migrations.RemoveField(
            model_name="deliveryman",
            name="IdentityType",
        ),
        migrations.AddField(
            model_name="deliveryman",
            name="Address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="deliveryman",
            name="BillBookScanCopy",
            field=models.FileField(upload_to="bill_book_files/"),
        ),
    ]
