# Generated by Django 5.2 on 2025-09-06 15:54

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0034_remove_deliveryman_deliverytype_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="business_plan",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="external_image_url",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="vat_and_tax",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="owner_email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="deliveryman",
            name="VehicleNumber",
            field=models.CharField(
                help_text="Enter the vehicle number in capital letters (e.g., BA 2 PA 1234 or 3-01-Pa-1234).",
                max_length=13,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        flags=re.RegexFlag["IGNORECASE"],
                        message="Enter a valid vehicle number (e.g. 'BA 01 PA 1234', 'BA-07-PA-1234', or '3-01-PA-1234').",
                        regex="^(?:[A-Z]{1,2}[-\\s]?\\d{1,2}[-\\s]?[A-Z]{1,2}[-\\s]?\\d{1,4}|\\d{1,2}-\\d{1,2}-[A-Z]{1,3}-\\d{1,4})$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="menu",
            field=models.FileField(
                blank=True, null=True, upload_to="restaurant/menus/"
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="restaurant_type",
            field=models.CharField(
                choices=[("local", "Local"), ("fine_dining", "Fine Dining")],
                default="local",
                max_length=20,
            ),
        ),
    ]
