# Generated by Django 5.2 on 2025-09-07 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0035_remove_restaurant_business_plan_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fooditem",
            name="external_image_url",
        ),
    ]
