# Generated by Django 5.2 on 2025-09-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0036_remove_fooditem_external_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="external_image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
