# Generated by Django 5.2 on 2025-09-10 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0037_fooditem_external_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverymanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('deliveryman', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='merchant.deliveryman')),
            ],
        ),
        migrations.CreateModel(
            name='GoToDashClickCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('go_to_dash_clicked', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='go_to_dash_check', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
