# Generated by Django 5.2 on 2025-10-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0038_deliverymanstatus_gotodashclickcheck"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="food_item",
        ),
        migrations.AddField(
            model_name="order",
            name="food_items",
            field=models.ManyToManyField(
                blank=True, related_name="orders", to="merchant.fooditem"
            ),
        ),
    ]
