# Generated by Django 5.2 on 2025-10-28 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0039_remove_order_food_item_order_food_items"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="food_items",
            new_name="food_item",
        ),
    ]
