# Generated by Django 5.2 on 2025-10-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0041_alter_order_options_remove_order_food_item_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="food_items",
            new_name="food_item",
        ),
    ]
