# Generated by Django 5.2 on 2025-11-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0042_rename_food_items_order_food_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="checked",
            field=models.BooleanField(default=False),
        ),
    ]
