# Generated by Django 5.2 on 2025-11-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0043_cart_checked"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("CashOnDelivery", "CashOnDelivery")],
                default="CashOnDelivery",
                max_length=50,
            ),
        ),
    ]
