# Generated by Django 5.2 on 2025-11-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0044_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
