# Generated by Django 5.2 on 2025-11-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0045_order_latitude_order_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_charge",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
