# Generated by Django 5.2 on 2025-11-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0046_order_delivery_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('PROCESSING', 'Processing'),
                    ('WAITING_FOR_DELIVERY', 'Waiting for Deliviery'),
                    ('OUT_FOR_DELIVERY', 'Out for Delivery'),
                    ('DELIVERED', 'Delivered'),
                    ('CANCELLED', 'Cancelled'),
                ],
                default='PENDING',
                max_length=20,
            ),
        ),
    ]
