# Generated by Django 5.2 on 2025-11-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0047_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliverypersonnel",
            name="current_order",
        ),
        migrations.RemoveField(
            model_name="deliverypersonnel",
            name="deliveryman_profile",
        ),
        migrations.AddField(
            model_name="deliverymanstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("on_delivery", "On Delivery"),
                    ("offline", "Offline"),
                ],
                default="offline",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Delivery",
        ),
        migrations.DeleteModel(
            name="DeliveryPersonnel",
        ),
    ]
