# Generated by Django 5.2 on 2025-11-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0048_remove_deliverypersonnel_current_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliverymanstatus",
            name="status",
        ),
        migrations.AddField(
            model_name="deliverymanstatus",
            name="on_delivery",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deliverymanstatus",
            name="online_status",
            field=models.CharField(
                choices=[("online", "Online"), ("offline", "Offline")],
                default="offline",
                max_length=10,
            ),
        ),
    ]
