# Generated by Django 5.2 on 2025-11-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0049_remove_deliverymanstatus_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliverymanstatus",
            name="online_status",
        ),
        migrations.AddField(
            model_name="deliverymanstatus",
            name="online",
            field=models.BooleanField(default=False),
        ),
    ]
