# Generated by Django 5.2 on 2025-11-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0050_remove_deliverymanstatus_online_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="assigned",
            field=models.BooleanField(default=False),
        ),
    ]
