# Generated by Django 5.2 on 2025-11-18 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0052_deliverynotification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliverynotification",
            old_name="is_read",
            new_name="read",
        ),
        migrations.AlterUniqueTogether(
            name="deliverynotification",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="deliverynotification",
            name="payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deliverynotification",
            name="deliveryman",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="merchant.deliveryman",
            ),
        ),
        migrations.AlterField(
            model_name="deliverynotification",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="merchant.order",
            ),
        ),
    ]
