# Generated by Django 5.2 on 2025-11-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0053_rename_is_read_deliverynotification_read_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynotification",
            name="read_by_another",
            field=models.BooleanField(default=False),
        ),
    ]
