# Generated by Django 5.2 on 2025-11-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0054_deliverynotification_read_by_another"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliverynotification",
            name="read_by_another",
        ),
    ]
