# Generated by Django 5.2 on 2025-11-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0055_remove_deliverynotification_read_by_another"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynotification",
            name="check_picked",
            field=models.BooleanField(default=False),
        ),
    ]
