# Generated by Django 5.2 on 2025-11-19 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0056_deliverynotification_check_picked"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="deliverynotification",
            unique_together={("deliveryman", "order")},
        ),
        migrations.AlterField(
            model_name="deliverynotification",
            name="deliveryman",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="merchant.deliveryman",
            ),
        ),
        migrations.AddIndex(
            model_name="deliverynotification",
            index=models.Index(
                fields=["deliveryman", "order"], name="merchant_de_deliver_18d44f_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="deliverynotification",
            name="check_picked",
        ),
        migrations.RemoveField(
            model_name="deliverynotification",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="deliverynotification",
            name="payload",
        ),
        migrations.RemoveField(
            model_name="deliverynotification",
            name="read",
        ),
    ]
