# Generated by Django 5.2 on 2025-11-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0057_alter_deliverynotification_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_location",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
