# Generated by Django 5.2 on 2025-11-28 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0059_orderhistory_orderitemhistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderhistory",
            name="original_order",
        ),
    ]
