# Generated by Django 5.2 on 2025-12-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0060_remove_orderhistory_original_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderhistory",
            name="original_order",
            field=models.CharField(
                blank=True,
                help_text="ID of the original order from the Order table before deletion.",
                max_length=50,
                null=True,
            ),
        ),
    ]
