# Generated by Django 5.2 on 2025-12-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0061_orderhistory_original_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
