from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.merchant_home_view, name='home'),
    path("email-sent/", views.email_sent_view, name='email-sent'),
    path("forgetpassword/", views.merchant_forgetpassword_view,
         name='forget_password'),
    path("merchant/reset-password/<uidb64>/<token>/",
         views.merchant_reset_password_view, name='merchant_reset_password'),
    path("restaurant-dashboard/", views.restaurant_dashboard,
         name='restaurant-dashboard'),
    path("deliveryman-dashboard/", views.deliveryman_dashboard,
         name='deliveryman-dashboard'),
    path("register-merchant/", views.merchant_form_register_view,
         name='merchant_register'),
    path("application-status/", views.application_status_view,
         name="application-status"),
    path("signup/", views.merchant_signup_view, name='merchant-signup'),
    path("merchant/login/", views.merchant_login_view, name="merchant-signin"),
    path("logout/", views.merchant_logout_view, name='merchant-logout'),
    path("lobby/", views.lobby_view, name='lobby'),
    path("order-receive/", views.order_receive_view, name='order-receive'),
    path("restaurant-orders/", views.restaurant_orders, name='restaurant-orders'),
    path("restaurant-menu-dishes/", views.restaurant_menu_dishes,
         name='restaurant-menu-dishes'),
    path("menu-dishes/update/<int:pk>/",
         views.menu_update_view, name="menu-update-view"),
    path("menu-dishes/delete/", views.delete_food_item, name="delete-food-item"),
    path("restaurant-customers/", views.restaurant_customers,
         name='restaurant-customers'),
    path("restaurant-settings/", views.restaurant_settings,
         name='restaurant-settings'),
    #     path("check-deliveryman/", views.check_deliveryman_status,
    #          name="check-deliveryman"),
    path("update-restaurant-bio/", views.update_restaurant_bio,
         name="update-restaurant-bio"),
    path("json/update-restaurant-bio/<int:id>/",
         views.restaurant_bio_json_response, name="update-restaurant-bio-json"),
    path("update-restaurant-profile-picture/", views.update_restaurant_profile_picture,
         name="update-restaurant-profile-picture"),
    path("update-restaurant-location/", views.update_restaurant_location,
         name="update-restaurant-location"),
    path("deliveryman-dashboard/", views.deliveryman_dashboard,
         name='deliveryman-dashboard'),
    path("deliveryman-new-orders/", views.deliveryman_new_orders,
         name='deliveryman-new-orders'),
    path("deliveryman-current-orders/", views.deliveryman_current_orders,
         name='deliveryman-current-orders'),
    path("deliveryman-history/", views.deliveryman_history,
         name='deliveryman-history'),
    path("deliveryman-profile/", views.deliveryman_profile,
         name='deliveryman-profile'),
    path("update-deliveryman-bio/", views.update_deliveryman_bio,
         name="update-deliveryman-bio"),
    path("json/update-deliveryman-bio/<int:id>/",
         views.deliveryman_bio_json_response, name="update-deliveryman-bio-json"),
    path("update-deliveryman-profile-picture/", views.update_deliveryman_profile_picture,
         name="update-deliveryman-profile-picture"),
    path("json/restaurant-orders-response/<int:id>/",
         views.restaurant_orders_json_response, name="restaurant-orders-json-response"),
    path('deliveryman-order-receive/', views.deliveryman_order_receive_view,
         name='deliveryman-order-receive'),
    path('json/deliveryman-delivery-requests/', views.deliveryman_delivery_requests_json_view,
         name="deliveryman-delivery-requests-json"),
    path('json/deliveryman-current-delivery/', views.deliveryman_current_delivery_json_view,
         name="deliveryman-current-delivery-json"),
    path('current-delivery-websocket/', views.current_delivery_websocket_view,
         name="current-delivery-websocket"),
    path('api/update-order-out-for-delivery-status/',
         views.bulk_update_order_status_api, name="bulk-update-order-status-api")
]
